### ISSUE TITLE
1.3.x Fails to Activate unless plone.app.collection is also active

### ISSUE THREAD

**Issue by ctxlken** [collective/collective.easyslider#18]
If your site does not yet have plone.app.collection active, then easyslider 1.3.x seems to fail on activation due to not finding the 'Collection' type (should optionally look for the Topic, type, it seems.)

Activating the new style Collections (plone.app.collection) allows easyslider to activate, but it's not ideal to have to activate the new collections type, as it is still a little buggy and/or missing some small bits of functionality that the old ATCTCollection had (such as the option to specify AND vs. OR conditions on filters.)

**Comment by vangheem** [comment]
This should have been fixed in 1.3.1.

**Comment by vangheem** [comment]
Oh wait, my bad. I misunderstood what you were saying. hmmm, we'll have to handle the install differently.

**Comment by ctxlken** [comment]
I was able to deactivate plone.app.collection just fine after activating collective.easyslider, but I would guess there are enough Plone installations out there that still don't have plone.app.collection active that many people will run into  this nasty activation error (it can't find the Collection 'meta_type'):

Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 580, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 512, in installProduct
- **traceback_info**: ('collective.easyslider',)
  Module Products.GenericSetup.tool, line 350, in runAllImportStepsFromProfile
- **traceback_info**: profile-collective.easyslider:default
  Module Products.GenericSetup.tool, line 1100, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1015, in _doRunImportStep
- **traceback_info**: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 225, in importTypesTool
  Module Products.GenericSetup.utils, line 834, in importObjects
- **traceback_info**: portal_types
  Module Products.GenericSetup.utils, line 509, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 210, in _importNode
  Module Products.GenericSetup.utils, line 570, in _initObjects
- **traceback_info**: ('Collection', '')
  ValueError: unknown meta_type ''
  2013-02-25 09:02:54 ERROR root Exception while rendering an error message
  Traceback (most recent call last):
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(*_kwargs)
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in **call**
    return Script.**call**(self, *args, *_kw)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in **call**
    return self._bindAndExec(args, kw, None)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Applications/plone424/buildout-cache/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(_args, *_kw)
  File "Script (Python)", line 34, in standard_error_message
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 79, in pt_render
    showtal=showtal)
  File "/Applications/plone424/buildout-cache/eggs/zope.pagetemplate-3.5.2-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 113, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations)()
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 888, in do_useMacro
    self.interpret(macro)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Applications/plone424/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 583, in do_setLocal_tal
    self.engine.setLocal(name, self.engine.evaluateValue(expr))
  File "/Applications/plone424/buildout-cache/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Products/PageTemplates/ZRPythonExpr.py", line 48, in **call**
    return eval(self._code, vars, {})
  File "PythonExpr", line 1, in <expression>
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFPlone-4.2.4-py2.7.egg/Products/CMFPlone/ActionsTool.py", line 111, in listFilteredActionsFor
    ignore_categories=ignore_categories
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFPlone-4.2.4-py2.7.egg/Products/CMFPlone/ActionsTool.py", line 80, in listActionInfos
    if check_condition and not ai['available']:
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/ActionInformation.py", line 206, in __getitem__
    value = self.data[key] = value(self._ec)
  File "/Applications/plone424/buildout-cache/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/Expression.py", line 47, in __call__
    res = compiled(econtext)
  File "/Applications/plone424/buildout-cache/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/expressions.py", line 217, in **call**
    return self._eval(econtext)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Products/PageTemplates/Expressions.py", line 147, in _eval
    ob = self._subexprs[-1](econtext)
  File "/Applications/plone424/buildout-cache/eggs/zope.tales-3.5.2-py2.7.egg/zope/tales/expressions.py", line 124, in _eval
    ob = self._traverser(ob, element, econtext)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/Products/PageTemplates/Expressions.py", line 74, in boboAwareZopeTraverse
    object = object.restrictedTraverse(name)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/OFS/Traversable.py", line 317, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "/Applications/plone424/buildout-cache/eggs/Zope2-2.13.19-py2.7.egg/OFS/Traversable.py", line 300, in unrestrictedTraverse
    raise e
  AttributeError: @@slider_util

**Comment by vangheem** [comment]
Alright, just released, can you give it a try?

**Comment by vangheem** [comment]
https://pypi.python.org/pypi/collective.easyslider/1.3.3

**Comment by ctxlken** [comment]
I get the same result/error, unfortunately.  In Add-ons, it showed as 1.3.3, and I confirmed that the instance startup script was loading this new egg and not the old one.

**Comment by vangheem** [comment]
Alright, can you try https://pypi.python.org/pypi/collective.easyslider/1.3.4 now?
